/**
 * SAMPLE CODE NOTICE
 * 
 * THIS SAMPLE CODE IS MADE AVAILABLE AS IS.  MICROSOFT MAKES NO WARRANTIES, WHETHER EXPRESS OR IMPLIED,
 * OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OR CONDITIONS OF MERCHANTABILITY.
 * THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SAMPLE CODE REMAINS WITH THE USER.
 * NO TECHNICAL SUPPORT IS PROVIDED.  YOU MAY NOT DISTRIBUTE THIS CODE UNLESS YOU HAVE A LICENSE AGREEMENT WITH MICROSOFT THAT ALLOWS YOU TO DO SO.
 */

module Contoso.Retail.Ecommerce.Sdk.Controls {
    ResourceStrings["fr"] = {
        String_1: "(FR) Shopping cart",
        String_2: "(FR) Product details",
        String_3: "(FR) Each",
        String_4: "(FR) Quantity",
        String_5: "(FR) Line total",
        String_6: "(FR) Remove",
        String_7: "(FR) Savings:",
        String_8: "(FR) Update quantity",
        String_9: "(FR) Order summary",
        String_10: "(FR) Subtotal:",
        String_11: "(FR) Shipping and handling:",
        String_12: "(FR) Order total:",
        String_13: "(FR) Total savings:",
        String_14: "(FR) Next step",
        String_15: "(FR) There are no items in your shopping cart. Please add items to the cart.",
        String_16: "(FR) Delivery information",
        String_17: "(FR) Delivery preference:",
        String_18: "(FR) Shipping address",
        String_19: "(FR) Shipping name",
        String_20: "(FR) Country/region",
        String_21: "(FR) United States",
        String_22: "(FR) Address",
        String_23: "(FR) City",
        String_24: "(FR) State/province",
        String_25: "(FR) ZIP/postal code",
        String_26: "(FR) Shipping method",
        String_27: "(FR) Get shipping options",
        String_28: "(FR) Previous step",
        String_29: "(FR) Name",
        String_30: "(FR) Billing information",
        String_31: "(FR) Contact information",
        String_32: "(FR) Email address",
        String_33: "(FR) Confirm email address",
        String_34: "(FR) Payment method",
        String_35: "(FR) Card number",
        String_36: "(FR) Card type",
        String_37: "(FR) Expiration month",
        String_38: "(FR) Expiration year",
        String_39: "(FR) CCID",
        String_40: "(FR) What is this?",
        String_41: "(FR) Payment amount",
        String_42: "(FR) Billing address",
        String_43: "(FR) Same as shipping address",
        String_44: "(FR) Address2",
        String_45: "(FR) Review and confirm",
        String_46: "(FR) Order information",
        String_47: "(FR) Edit",
        String_48: "(FR) Credit card",
        String_49: "(FR) Checkout",
        String_50: "(FR) You have not added any promotion code to your order",
        String_51: "(FR) Tax:",
        String_52: "(FR) Submit order",
        String_53: "(FR) Thank you for your order",
        String_54: "(FR) Your order confirmation number is ",
        String_55: "(FR) Street",
        String_56: "(FR) State",
        String_57: "(FR) Zipcode",
        String_58: "(FR) Email",
        String_59: "(FR) Payment",
        String_60: "(FR) CardNumber",
        String_61: "(FR) Please select shipping method",
        String_62: "(FR) The confirm email address must match the email address.",
        String_63: "(FR) Sorry, something went wrong. The shopping cart information couldn't be retrieved. Please refresh the page and try again.",
        String_64: "(FR) Sorry, something went wrong. The product was not removed from the cart successfully. Please refresh the page and try again.",
        String_65: "(FR) Sorry, something went wrong. The product quantity couldn't be updated. Please refresh the page and try again.",
        String_66: "(FR) Sorry, something went wrong. Delivery methods could not be retrieved. Please refresh the page and try again.",
        String_67: "(FR) Sorry, something went wrong. The shipping information was not stored successfully. Please refresh the page and try again.",
        String_68: "(FR) Sorry, something went wrong. The payment card type information was not retrieved successfully. Please refresh the page and try again.",
        String_69: "(FR) Sorry, something went wrong. The order submission was not successful. Please refresh the page and try again.",
        String_70: "(FR) Invalid parameter",
        String_71: "(FR) validatorType attribute is not provided for validator binding.",
        String_72: "(FR) Use text characters only. Numbers, spaces, and special characters are not allowed.",
        String_73: "(FR) Use text characters only. Numbers, spaces, and special characters are not allowed.",
        String_74: "(FR) The quantity field cannot be empty",
        String_75: "(FR) Select delivery method.",
        String_76: "(FR) The email address is invalid.",
        String_77: "(FR) Please enter the name.",
        String_78: "(FR) Please enter the street number.",
        String_79: "(FR) Please enter the address.",
        String_80: "(FR) Please enter the city.",
        String_81: "(FR) Please enter the zip/postal code.",
        String_82: "(FR) Please enter the state.",
        String_83: "(FR) Please enter the country.",
        String_84: "(FR) Please specify a payment card name.",
        String_85: "(FR) Please enter a valid card number.",
        String_86: "(FR) Please enter a valid CCID.",
        String_87: "(FR) Please specify a valid amount.",
        String_88: "(FR) {0} PRODUCT(S)",
        String_89: "(FR) Included",
        String_90: "(FR) Color: {0}",
        String_91: "(FR) Size: {0}",
        String_92: "(FR) Style: {0}",
        String_93: "(FR) Sorry, something went wrong. The promotion code could not be added successfully. Please refresh the page and try again.",
        String_94: "(FR) Sorry, something went wrong. The promotion code could not be removed successfully. Please refresh the page and try again.",
        String_95: "(FR) Apply",
        String_96: "(FR) Promotion Codes",
        String_97: "(FR) Please enter a promotion code",
        String_98: "(FR) Sorry, something went wrong. The channel configuration could not be retrieved successfully. Please refresh the page and try again.",
        String_99: "(FR) Ship items",
        String_100: "(FR) Pick up in store",
        String_101: "(FR) Select delivery options by item",
        String_102: "(FR) Find a store",
        String_103: "(FR) miles",
        String_104: "(FR) Available stores",
        String_105: "(FR) Store",
        String_106: "(FR) Distance",
        String_107: "(FR) Products are not available for pick up in the stores around the location you searched. Please update your delivery preferences and try again.",
        String_108: "(FR) Sorry, something went wrong. An error occurred while trying to get stores. Please refresh the page and try again.",
        String_109: "(FR) Sorry, we were not able to decipher the address you gave us.  Please enter a valid Address",
        String_110: "(FR) Sorry, something went wrong. An error has occured while looking up the address you provided. Please refresh the page and try again.",
        String_111: "(FR) Products are not available in this store",
        String_112: "(FR) Product availability:",
        String_113: "(FR) Products are not available in the selected store, Please select a different store",
        String_114: "(FR) Please select a store for pick up",
        String_115: "(FR) Store address",
        String_116: "(FR) Send to me",
        String_117: "(FR) Optional note",
        String_118: "(FR) Please enter email address for gift card delivery",
        String_119: "(FR) Sorry, something went wrong. An error occurred while trying to get the email address. Please enter the email address in the text box below",
        String_120: "(FR) Enter the shipping address and then click get shipping options to view the shipping options that are available for your area.",
        String_121: "(FR) Delivery method",
        String_122: "(FR) Select your delivery preference",
        String_123: "(FR) Cancel",
        String_124: "(FR) Done",
        String_125: "(FR) for product: {0}",
        String_126: "(FR) Please select delivery preference for product {0}",
        String_127: "(FR) Add credit card",
        String_128: "(FR) Gift card",
        String_129: "(FR) Add gift card",
        String_130: "(FR) Loyalty card",
        String_131: "(FR) Add loyalty card",
        String_132: "(FR) Payment information",
        String_133: "(FR) Payment total:",
        String_134: "(FR) Order total:",
        String_135: "(FR) Gift card does not exist",
        String_136: "(FR) Gift card balance",
        String_137: "(FR) Card details",
        String_138: "(FR) Sorry, something went wrong. An error occurred while trying to get payment methods supported by the store. Please refresh the page and try again.",
        String_139: "(FR) Please select payment method",
        String_140: "(FR) The expiration date is not valid. Please select valid expiration month and year and then try again",
        String_141: "(FR) Please enter a valid gift card number",
        String_142: "(FR) Get gift card balance",
        String_143: "(FR) Apply full amount",
        String_144: "(FR) Please enter a gift card number",
        String_145: "(FR) Sorry, something went wrong. An error occurred while trying to get gift card balance. Please refresh the page and try again.",
        String_146: "(FR) Gift card payment amount cannot be zero",
        String_147: "(FR) Gift card payment amount is more than order total",
        String_148: "(FR) Gift card does not have sufficient balance",
        String_149: "(FR) Payment amount is different from the order total",
        String_150: "(FR) Sorry, something went wrong. An error occurred while trying to get loyalty card information. Please refresh the page and try again.",
        String_151: "(FR) Please enter a valid loyalty card number",
        String_152: "(FR) Loyalty card payment amount cannot be zero",
        String_153: "(FR) Loyalty card payment amount is more than order total",
        String_154: "(FR) The loyalty card is blocked",
        String_155: "(FR) The loyalty card is not allowed for payment",
        String_156: "(FR) The loyalty payment amount exceeds what is allowed for this loyalty card in this transaction",
        String_157: "(FR) The loyalty card number does not exist",
        String_158: "(FR) Please select delivery preference",
        String_159: "(FR) Please select a delivery preference...",
        String_160: "(FR) Sorry, something went wrong. An error occurred while trying to get delivery methods information. Please refresh the page and try again.",
        String_161: "(FR) Select address...",
        String_162: "(FR) You have not added loyalty card number to your order",
        String_163: "(FR) Enter a reward card for the current order. You can include only one reward card per order",
        String_164: "(FR) Sorry, something went wrong. An error occurred while trying to update reward card id in cart. Please refresh the page and try again.",
        String_165: "(FR) Sorry, something went wrong. An error occurred while retrieving the country region information. Please refresh the page and try again.",
        String_166: "(FR) TBD",
        String_167: "(FR) Mini Cart",
        String_168: "(FR) Ordering FAQ",
        String_169: "(FR) Return policy",
        String_170: "(FR) Store locator tool",
        String_171: "(FR) Continue shopping",
        String_172: "(FR) Cart Order Total",
        String_173: "(FR) View full cart contents",
        String_174: "(FR) Quantity:",
        String_175: "(FR) Added to your cart:",
        String_176: "(FR) Loading ...",
        String_177: "(FR) Sorry, something went wrong. The cart's promotion information couldn't be retrieved. Please refresh the page and try again.",
        String_178: "(FR) Delivery method",
        String_179: "(FR) Updating shopping cart ...",
        String_180: "(FR) Submitting order ...",
        String_181: "(FR) Discount code",
        String_182: "(FR) Add coupon code",
        String_183: "(FR) Enter a discount code",
        String_184: "(FR) Please enter a valid discount code",
        String_185: "(FR) Sorry, something went wrong. An error occurred while retrieving the state/province information. Please refresh the page and try again.",
        String_186: "(FR) Edit reward card",
        String_187: "(FR) Reward card",
        String_188: "(FR) Add discount code",
        String_189: "(FR) Select country/region",
        String_190: "(FR) Select state/province",
        String_191: "(FR) You have selected multiple delivery methods for this order",
        String_192: "(FR) 01-January",
        String_193: "(FR) 02-February",
        String_194: "(FR) 03-March",
        String_195: "(FR) 04-April",
        String_196: "(FR) 05-May",
        String_197: "(FR) 06-June",
        String_198: "(FR) 07-July",
        String_199: "(FR) 08-August",
        String_200: "(FR) 09-September",
        String_201: "(FR) 10-October",
        String_202: "(FR) 11-November",
        String_203: "(FR) 12-December",
        String_204: "(FR) The number string has more than one decimal operator.",
        String_205: "(FR) Estimated total: ",
        String_206: "(FR) The actual tax amount will be calculated based on the applicable state and local sales taxes when your delivery preference is selected.",
        String_207: "(FR) The shipping and handling charges will be calculated based on delivery preference and recipient address(es) provided.",
        String_208: "(FR) Included",
        String_209: "(FR) Sorry, something went wrong. An error occurred while retrieving signed-in customer's information. Please refresh the page and try again.",
        String_210: "(FR) Sorry, something went wrong. We were unable to obtain the card payment accept result. Please refresh the page and try again.",
        String_211: "(FR) Sorry, something went wrong. We were unable to obtain the card payment accept page url. Please refresh the page and try again.",
        String_212: "(FR) The specified zip code is invalid.",
        String_213: "(FR) The specified state is invalid.",
        String_214: "(FR) The specified city is invalid.",
        String_215: "(FR) The shipping address is not valid.",
        String_216: "(FR) The loyalty card number that you entered is invalid.",
        String_217: "(FR) The loyalty card is blocked.",
        String_218: "(FR) The loyalty card can't be added to the transaction because the customer on the loyalty card is different than the customer on the transaction. Either change the customer on the transaction or select a different loyalty card.",
        String_219: "(FR) This loyalty card is not eligible to redeem loyalty points for this transaction.",
        String_220: "(FR) There are not enough loyalty reward points available on the loyalty card.",
        String_221: "(FR) The service call is taking longer than expected. Please wait for it to respond or refresh the page and try again.",
        String_222: "(FR) IMPORTANT NOTICE:",
        String_223: "(FR) This form is provided by your designated third-party payment provider.  By clicking \"Next\" you acknowledge your information will be transmitted directly to your payment provider, and will be handled in accordance with the terms and conditions and privacy statement that you agreed to with your payment provider.  Microsoft does not collect, store, or transmit any of your payment card information, or provide rights for third-party products or services.",
        String_224: "(FR) Order date",
        String_225: "(FR) Order number",
        String_226: "(FR) Order status",
        String_227: "(FR) Recent orders",
        String_228: "(FR) My account",
        String_229: "(FR) Order history",
        String_230: "(FR) Sorry, something went wrong. We were unable to obtain your order history. Please refresh the page and try again.",
        String_231: "(FR) There are no orders to display.",
        String_232: "(FR) Sorry, something went wrong. An error occurred while trying to update loyalty card information. Please refresh the page and try again.",
        String_233: "(FR) Sorry, something went wrong. An error occurred while trying to get user login information. Please refresh the page and try again.",
        String_234: "(FR) Address book",
        String_235: "(FR) There are no addresses.",
        String_236: "(FR) Order detail: ",
        String_237: "(FR) Sorry, something went wrong. An error occurred while trying to get the order details information. Please refresh the page and try again.",
        String_238: "(FR) Line total:",
        String_239: "(FR) Delivery method: ",
        String_240: "Processing",
        String_241: "Order number: ",
        String_242: "Order status: ",

        //======================================================== PAYMENT EXCEPTION ERROR CODES [301 - 500] =========================================================================================
        String_301: "(FR) Invalid Operation",
        String_302: "(FR) The application has encountered an unknown error.",
        String_303: "(FR) Errors found, check the detailed error results for additional information.",
        String_304: "(FR) Errors found, payment not authorized. Check the detailed error results for additional information.",
        String_305: "(FR) User aborted",
        String_306: "(FR) Locale not supported",
        String_307: "(FR) Invalid merchant property",
        String_308: "(FR) There was an error communicating with the payment provider. Retry your request.",
        String_309: "(FR) The specified card type is not supported",
        String_310: "(FR) Voice authorization not supported.",
        String_311: "(FR) Re-authorizations are not supported by this payment provider.",
        String_312: "(FR) The payment provider assigned does not support multiple captures against a single authorization.",
        String_313: "(FR) Batch capture is not supported.",
        String_314: "(FR) Invalid CurrencyCode",
        String_315: "(FR) Invalid CountryOrRegion",
        String_316: "(FR) Cannot reauthorize a transaction against which funds have already been captured.",
        String_317: "(FR) Cannot reauthorize a transaction that has been voided.",
        String_318: "(FR) The payment provider does not support immediate capture.",
        String_319: "(FR) Credit card expired",
        String_320: "(FR) Refer to card issuer",
        String_321: "(FR) There was no reply from the payment provider for this transaction. Retry the operation.",
        String_322: "(FR) The transaction was declined by the payment provider. The payment provider requests that you hold the card and call the card issuer.",
        String_323: "(FR) Invalid Amount",
        String_324: "(FR) AccountNumber has an invalid length",
        String_325: "(FR) The payment provider rejected the transaction with the following message: The transaction has already been reversed",
        String_326: "(FR) Invalid PIN",
        String_327: "(FR) Invalid AccountNumber",
        String_328: "(FR) Invalid CVV",
        String_329: "(FR) Cashback is not supported for this transaction.",
        String_330: "(FR) Invalid CardType",
        String_331: "(FR) The transaction was declined by the payment provider.",
        String_332: "(FR) Encryption error, check the detailed error results for additional information.",
        String_333: "(FR) The payment provider rejected the transaction with this message: No action taken",
        String_334: "(FR) The payment provider rejected the transaction with this message: No such issuer",
        String_335: "(FR) Invalid PIN. You have exceeded the allowed number of attempts to authenticate and this account has been locked.",
        String_336: "(FR) The payment provider rejected the transaction with this message: Security violation at the processor",
        String_337: "(FR) The payment provider rejected the transaction with this message: Service not allowed",
        String_338: "(FR) The payment provider rejected the transaction with this message: Customer stopped recurring",
        String_339: "(FR) The transaction was rejected due to an invalid PIN.",
        String_340: "(FR) The transaction was rejected due to an invalid card verification value (CVV/CVV2).",
        String_341: "(FR) The payment transaction duplicates a previous payment transaction. The duplicate transaction was not processed.",
        String_342: "(FR) The payment provider rejected the transaction with this message: Re-Enter",
        String_343: "(FR) Amount exceeds the maximum allowed amount for a payment",
        String_344: "(FR) Authorization for this payment transaction has expired. You will need to re-authorize before capturing funds.",
        String_345: "(FR) The payment provider rejected the capture because the entire amount of the original authorization has already been captured.",
        String_346: "(FR) Cannot process payments against a transaction that has been voided.",
        String_347: "(FR) The payment provider rejected the batch as a duplicate.",
        String_348: "(FR) Authorization failed",
        String_349: "(FR) The merchant configuration is invalid.",
        String_350: "(FR) Invalid Expiration Date",
        String_351: "(FR) Invalid Firstname",
        String_352: "(FR) Invalid LastName",
        String_353: "(FR) The payment provider declined this transaction.",
        String_354: "(FR) Invalid Address",
        String_355: "(FR) The transaction was rejected because a Card Verification Value (CVV/CVV2) is required and was not provided.",
        String_356: "(FR) CardType is an unsupported type",
        String_357: "(FR) The payment provider rejected the transaction because the invoice number is a duplicate of a previous transaction.",
        String_358: "(FR) Payment provider indicated that this transaction appears to be a duplicate. The transaction was not processed.",
        String_359: "(FR) The payment provider selected for this payment type requires refunds to link to an existing payment capture. Reference a capture transaction using the CaptureTransactionGuid field.",
        String_360: "(FR) Encryption unavailable",
        String_361: "(FR) The transaction was declined due to an invalid card verification value (CVV/CVV2).",
        String_362: "(FR) The Merchant Id is invalid.",
        String_363: "(FR) The transaction was not allowed.",
        String_364: "(FR) The terminal has not been registered. Check your terminal Id setting.",
        String_365: "(FR) Invalid effective date",
        String_366: "(FR) Insufficient funds for the transaction.",
        String_367: "(FR) The payment provider rejected the transaction with this message: Reauthorization maximum reached",
        String_368: "(FR) The payment provider rejected the transaction with this message: Reauthorization Not Allowed",
        String_369: "(FR) Invalid Date of Birth",
        String_370: "(FR) The transaction requires a smaller amount.",
        String_371: "(FR) Host key error",
        String_372: "(FR) Invalid cashback amount",
        String_373: "(FR) Invalid transaction",
        String_374: "(FR) Immediate transaction type required",
        String_375: "(FR) Immediate transaction type required with MAC",
        String_376: "(FR) MAC Required for this transaction",
        String_377: "(FR) The bank card property in the request has not been set.",
        String_378: "(FR) Invalid request message sent.",
        String_379: "(FR) Invalid transaction fee",
        String_380: "(FR) No checking account",
        String_381: "(FR) No savings account",
        String_382: "(FR) Restricted card temporarily disallowed from interchange.",
        String_383: "(FR) MAC security failure",
        String_384: "(FR) Payment transaction exceeds withdrawal frequency limit.",
        String_385: "(FR) Invalid capture date",
        String_386: "(FR) No keys available",
        String_387: "(FR) KME sync error",
        String_388: "(FR) KPE sync error",
        String_389: "(FR) KMAC sync error",
        String_390: "(FR) Payment transaction has exceeded the limit of resubmits.",
        String_391: "(FR) System problem error",
        String_392: "(FR) Account number not found for row {0}.",
        String_393: "(FR) Invalid TokenInfo parameter for row {0}.",
        String_394: "(FR) Exception {0} occurred for row {1}.",
        String_395: "(FR) The transaction amount exceeds the remaining authorized amount.",
        String_396: "(FR) Invalid TenderAccountNumber",
        String_397: "(FR) The card track data is invalid.",
        String_398: "(FR) The payment accept page result access code is invalid.",
        String_399: "(FR) Sorry, something went wrong. Payment exception has occured. Please refresh the page and try again or try another payment method.",
        //======================================================== END PAYMENT EXCEPTION ERROR CODES [301 - 500] =========================================================================================

        //======================================================== RETAIL SERVER ERROR CODES [500 - 700] =================================================================================================
        String_501: "(FR) Sorry something went wrong, we cannot process your request at this time. Please try again later.",
        String_502: "(FR) The specified ID already exists.",
        String_503: "(FR) There is an insufficient quantity of the product on-hand.",
        String_504: "(FR) The cart line add is not valid.",
        String_505: "(FR) The format of the specified data is not valid.",
        String_506: "(FR) The change version requested and stored do not match.",
        String_507: "(FR) The specified ID was not found.",
        String_508: "(FR) Required value is missing.",
        String_509: "(FR) The specified request type is unknown.",
        String_510: "(FR) The language specified is not supported.",
        String_511: "(FR) The specified value is out of range.",
        String_512: "(FR) The cart was updated by another session. Please refresh and retry.",
        String_513: "(FR) A communication error occurred.",
        String_514: "(FR) Runtime components for the application are missing.",
        String_515: "(FR) Configuration settings are missing.",
        String_516: "(FR) Duplicate notification handlers have been encountered.",
        String_517: "(FR) The unit of measure is not set for the product.",
        String_518: "(FR) An error occurred communicating with an external provider.",
        String_519: "(FR) Data returned from headquarters could not be parsed.",
        String_520: "(FR) There is nothing in the cart. Add a product to the cart, and then try again.",
        String_521: "(FR) The channel configuration is not properly configured.",
        String_522: "(FR) The configuration key is not valid.",
        String_523: "(FR) The database connection string is not valid.",
        String_524: "(FR) The runtime pipeline has not been correctly configured.",
        String_525: "(FR) One or more providers are not correctly configured.",
        String_526: "(FR) The runtime context is not valid.  This is most likely a coding error.",
        String_527: "(FR) The response returned from the server is not valid.",
        String_528: "(FR) One or more runtime components failed to initialize.",
        String_529: "(FR) The service cannot be found.",
        String_530: "(FR) The address provided does not match any sales tax group. This is likely a sales tax group configuration issue.",
        String_531: "(FR) No default notification handler has been configured.",
        String_532: "(FR) The delivery options could not be found.",
        String_533: "(FR) No inventory can be found for this product.",
        String_534: "(FR) A validation error occurred.",
        String_535: "(FR) The coupon is only valid for the current session.",
        String_536: "(FR) A database error has occurred.",
        String_537: "(FR) The discount amount for a line item has changed.",
        String_538: "(FR) An ID mismatch has occurred.",
        String_539: "(FR) There is an insufficient quantity of the product available.",
        String_540: "(FR) The price cannot be found for the product.",
        String_541: "(FR) The request passed to the service is not valid.",
        String_542: "(FR) A SQL command is not valid. This is most likely a coding error.",
        String_543: "(FR) One or more products are discontinued for the given channel.",
        String_544: "(FR) There is a mismatch between the object to be saved and the object in the database. Please try again.",
        String_545: "(FR) There is an error communicating with the provider.",
        String_546: "(FR) The requested product is out of stock.",
        String_547: "(FR) The unit of measure conversion cannot be found.",
        String_548: "(FR) Default customer cannot be found.",
        String_549: "(FR) The given currency is not supported.",
        String_550: "(FR) The number that was entered for the credit card number isn't valid. Enter a valid card number.",
        String_551: "(FR) The channel is invalid.",
        String_552: "(FR) The server api version is not supported",
        String_553: "(FR) Declined. The payment couldn't be authorized.",
        String_554: "(FR) That loyalty card number is not available. Please try a different card number.",
        String_555: "(FR) The customer was not found. Please try again.",
        String_556: "(FR) There was an error processing your request. Please try again later.",
        String_557: "(FR) The transaction can't contain more than one loyalty payment line.",
        String_558: "(FR) Amount due must be paid before checkout.",
        String_559: "(FR) The payment information is either missing information or it is incorrect. Verify the payment information and then try again.",
        String_560: "(FR) The address is either missing information or it is incorrect. Verify the address and then try again.",
        String_561: "(FR) The amount exceeds the balance on the gift card. Enter a different amount and then try again.",
        String_562: "(FR) You cannot perform two operations with the same gift card in a single transaction.",
        String_563: "(FR) The quantity of item is not valid for the unit of measure. Please enter a different value and try again.",
        String_564: "(FR) An item cannot be added to a sales transaction. The maximum quantity has been reached.",
        String_565: "(FR) The unit of measure symbol is invalid.",
        String_566: "(FR) The shopping cart is not found.",
        String_567: "(FR) An error occurred while trying to unlock the gift card.",
        String_568: "(FR) There was an error when changing the password.",
        String_569: "(FR) There was an error when resetting the password.",
        String_570: "(FR) There was a connectivity error. Please try again later.",
        String_571: "(FR) You can't add a line item to the sale with a quantity that is less than or equal to zero. Enter a quantity that is greater than zero and then try again.",
        String_572: "(FR) Sorry, the user session has expired or is invalid. Please logon again.",
        String_573: "(FR) The amount cannot be zero or negative.",
        String_574: "(FR) The password is invalid. Please try again.",
        String_575: "(FR) Overpayment is not allowed for this payment method. Enter an amount that is either less than or equal to the amount due or change the payment method, and then try again.",
        String_576: "(FR) The payment amount exceeds the maximum amount that is allowed per line.  Enter a different payment amount and then try again.",
        String_577: "(FR) The payment amount exceeds the maximum amount that is allowed for the transaction.  Enter a different payment amount and then try again.",
        String_578: "(FR) The payment amount is less than the minimum amount that is allowed per line. Enter a different payment amount and then try again.",
        String_579: "(FR) The payment amount is less than the minimum amount that is allowed for the transaction. Enter a different payment amount and then try again.",
        String_580: "(FR) The payment amount must be equal to or greater than the remaining balance. Enter a different payment amount and then try again.",
        String_581: "(FR) Selected product has not been activated for sale.",
        String_582: "(FR) Selected product is blocked and cannot be sold.",
        String_583: "(FR) Invalid configuration, please try again.",
        String_584: "(FR) A data validation error has occurred, please try again.",
        String_585: "(FR) A storage error has occurred, please try again.",
        String_586: "(FR) A communication error has occurred, please try again.",
        String_587: "(FR) A real time service call failure has occurred, please try again.",
        String_588: "(FR) Real time service call has timed out. Please try again.",
        String_589: "(FR) Real time service exception. Please try again.",
        String_590: "(FR) Real time service authentication failure. Please try again.",
        String_591: "(FR) Real time service call is not supported. Please try again.",
        String_592: "(FR) Real time service call is incorrect. Please try again.",
        String_593: "(FR) Unable to find delivery preferences. Please try again.",
        String_594: "(FR) The tender type configuration is not found. Please try again.",
        String_595: "(FR) Payment connector is not found.",
        String_596: "(FR) The given sales line is invalid. Required value is missing.",
        String_597: "(FR) The delivery mode is invalid.",
        String_598: "(FR) The email address is invalid.",
        String_599: "(FR) The delivery preference type is invalid.",
        String_600: "(FR) The transaction status is invalid.",
        String_601: "(FR) The cart is not active. Please refresh the page and try again.",
        String_602: "(FR) Multiple credit card payment is not supported.",
        String_603: "(FR) The cart type is invalid. Please try again.",
        String_604: "(FR) The sales line update is invalid. Please try again.",
        String_605: "(FR) The product is invalid. Please try again.",
        String_606: "(FR) Invalid cart inventory location id. Please try again.",
        String_607: "(FR) Invalid cart lines aggregation error. Please try again.",
        String_608: "(FR) Conflicting cart line operation. Please try again.",

        //======================================================== END RETAIL SERVER ERROR CODES [500 - 700] =============================================================================================
    };
}