/**
 * SAMPLE CODE NOTICE
 * 
 * THIS SAMPLE CODE IS MADE AVAILABLE AS IS.  MICROSOFT MAKES NO WARRANTIES, WHETHER EXPRESS OR IMPLIED,
 * OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OR CONDITIONS OF MERCHANTABILITY.
 * THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SAMPLE CODE REMAINS WITH THE USER.
 * NO TECHNICAL SUPPORT IS PROVIDED.  YOU MAY NOT DISTRIBUTE THIS CODE UNLESS YOU HAVE A LICENSE AGREEMENT WITH MICROSOFT THAT ALLOWS YOU TO DO SO.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Retail.Ecommerce.Sdk.Core.Publishing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Retail.Ecommerce.Sdk.Core.Publishing.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products=&apos;{0}&apos;; Total CRT read time=&apos;{1}&apos;..
        /// </summary>
        internal static string AllCatalogsReadCompleted {
            get {
                return ResourceManager.GetString("AllCatalogsReadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed reading catalog &apos;{0}&apos;. Products in catalog=&apos;{1}&apos;; Total products=&apos;{2}&apos;; Total CRT read time=&apos;{3}&apos;..
        /// </summary>
        internal static string CatalogReadCompleted {
            get {
                return ResourceManager.GetString("CatalogReadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProducts took {0}. Changes detected={1}.
        /// </summary>
        internal static string Duration_DeleteProducts {
            get {
                return ResourceManager.GetString("Duration_DeleteProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetNotExistingCatalogs took {0} and returned {1} SP Lists and {2} catalogs..
        /// </summary>
        internal static string Duration_GetNotExistingCatalogs {
            get {
                return ResourceManager.GetString("Duration_GetNotExistingCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetNotExistingLanguages took {0} and returned {1} SP Lists and {2} languages..
        /// </summary>
        internal static string Duration_GetNotExistingLanguages {
            get {
                return ResourceManager.GetString("Duration_GetNotExistingLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadAllListingsMap took {0} to load {1} listings for {2} catalogs..
        /// </summary>
        internal static string Duration_LoadListingsMap {
            get {
                return ResourceManager.GetString("Duration_LoadListingsMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChannelCatalogManager.DeleteListingsByCatalogs took {0}..
        /// </summary>
        internal static string Duration_Manager_DeleteListingsByCatalogs {
            get {
                return ResourceManager.GetString("Duration_Manager_DeleteListingsByCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChannelCatalogManager.DeleteListingsByCompositeIds took {0} to remove {1} listings..
        /// </summary>
        internal static string Duration_Manager_DeleteListingsByCompositeIds {
            get {
                return ResourceManager.GetString("Duration_Manager_DeleteListingsByCompositeIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishingProcessor.DeleteListingsByCatalogs took {0}..
        /// </summary>
        internal static string Duration_Processor_DeleteListingsByCatalogs {
            get {
                return ResourceManager.GetString("Duration_Processor_DeleteListingsByCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishingProcessor.DeleteListingsByLanguages took {0}..
        /// </summary>
        internal static string Duration_Processor_DeleteListingsByCompositeIds {
            get {
                return ResourceManager.GetString("Duration_Processor_DeleteListingsByCompositeIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishingProcessor.DeleteListingsByLanguages took {0}..
        /// </summary>
        internal static string Duration_Processor_DeleteListingsByLanguage {
            get {
                return ResourceManager.GetString("Duration_Processor_DeleteListingsByLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChannelCatalogManager.DeleteListingsByLanguages took {0}..
        /// </summary>
        internal static string Duration_Processor_DeleteListingsByLanguages {
            get {
                return ResourceManager.GetString("Duration_Processor_DeleteListingsByLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadChangedProducts took {0} and returned {1} IDs..
        /// </summary>
        internal static string Duration_ReadChangedProducts {
            get {
                return ResourceManager.GetString("Duration_ReadChangedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerifyProductExistence took {0} to verify {1} of IDs starting with index {2}. Total number of IDs:{3}. Number of returned IDs:{4}..
        /// </summary>
        internal static string Duration_VerifyProductExistence {
            get {
                return ResourceManager.GetString("Duration_VerifyProductExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not proceed to catalog publishing because channel has not been published successfully. Channel publishing status: {0}. Status message: &apos;{1}&apos;. If you cannot identify the source of the issue by reading this message then look for the error details in Event Viewer around the time specified in the status message. Once you resolve the root cause of the channel publishing issue then re-publish the channel in Microsoft Dynamics AX..
        /// </summary>
        internal static string ErrorChannelNotInPublishedState {
            get {
                return ResourceManager.GetString("ErrorChannelNotInPublishedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Time of the failure: {1}.
        /// </summary>
        internal static string ErrorChannelPublishingFailed {
            get {
                return ResourceManager.GetString("ErrorChannelPublishingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel doesn&apos;t have any categories..
        /// </summary>
        internal static string ErrorNoNavigationCategories {
            get {
                return ResourceManager.GetString("ErrorNoNavigationCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel doesn&apos;t have any listing attributes. Make sure they are included in AX channel management UI..
        /// </summary>
        internal static string ErrorNoSchemaAttributes {
            get {
                return ResourceManager.GetString("ErrorNoSchemaAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read {0} listing attributes..
        /// </summary>
        internal static string NumberOfReadAttributes {
            get {
                return ResourceManager.GetString("NumberOfReadAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read {0} categories and {1} categories&apos; attributes..
        /// </summary>
        internal static string NumberOfReadCategoriesAndTheirAttributes {
            get {
                return ResourceManager.GetString("NumberOfReadCategoriesAndTheirAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of read products in page={0}. Duration={1}..
        /// </summary>
        internal static string NumberOfReadProductsInPage {
            get {
                return ResourceManager.GetString("NumberOfReadProductsInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page of changed products read. Catalog=&apos;{0}&apos;; Products in catalog=&apos;{1}&apos;; Total products=&apos;{2}&apos;; Total CRT read time=&apos;{3}&apos;..
        /// </summary>
        internal static string NumberOfReadProductsInPageSummary {
            get {
                return ResourceManager.GetString("NumberOfReadProductsInPageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing updated products from catalog &apos;{0}&apos; (name: &apos;{1}&apos;, description: &apos;{2}&apos;.).
        /// </summary>
        internal static string ProductCatalogToPublish {
            get {
                return ResourceManager.GetString("ProductCatalogToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start retrieving products for the catalog &apos;{0}&apos;..
        /// </summary>
        internal static string StartReadProductsFromCatalog {
            get {
                return ResourceManager.GetString("StartReadProductsFromCatalog", resourceCulture);
            }
        }
    }
}
