/**
 * SAMPLE CODE NOTICE
 * 
 * THIS SAMPLE CODE IS MADE AVAILABLE AS IS.  MICROSOFT MAKES NO WARRANTIES, WHETHER EXPRESS OR IMPLIED,
 * OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OR CONDITIONS OF MERCHANTABILITY.
 * THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SAMPLE CODE REMAINS WITH THE USER.
 * NO TECHNICAL SUPPORT IS PROVIDED.  YOU MAY NOT DISTRIBUTE THIS CODE UNLESS YOU HAVE A LICENSE AGREEMENT WITH MICROSOFT THAT ALLOWS YOU TO DO SO.
 */

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "DR1721:AssertSdkExtensionMethodsNotCalledInProductCode", Scope = "member", Target = "Microsoft.Dynamics.Commerce.Runtime.StoreHoursSample.StoreHoursDataService.#Execute(Microsoft.Dynamics.Commerce.Runtime.Messages.Request)", Justification = "This is code to demonstrate an extension.")]
