/**
 * SAMPLE CODE NOTICE
 * 
 * THIS SAMPLE CODE IS MADE AVAILABLE AS IS.  MICROSOFT MAKES NO WARRANTIES, WHETHER EXPRESS OR IMPLIED,
 * OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OR CONDITIONS OF MERCHANTABILITY.
 * THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SAMPLE CODE REMAINS WITH THE USER.
 * NO TECHNICAL SUPPORT IS PROVIDED.  YOU MAY NOT DISTRIBUTE THIS CODE UNLESS YOU HAVE A LICENSE AGREEMENT WITH MICROSOFT THAT ALLOWS YOU TO DO SO.
 */

module Commerce.Proxy.Common {
    "use strict";

    /**
     * Interface for data service request.
     */
    export interface IDataServiceRequest {

        /**
         * Locale for the current data service request.
         */
        locale: string;

        /**
         * Request Identifier.
         * Autogenerated unique identifier if executed in batch. Used to fetch the response from batch result array.
         */
        id(): number;

        /**
         * Execute the request.
         * @param {any} callerContext The caller context.
         * @return {IAsyncResult<T>} The async result.
         */
        execute<T>(callerContext: any): IAsyncResult<T>;

        /**
         * Executes the batch requests.
         * @param {IDataServiceRequest[]} requests The collection of requests to execute.
         * @param {any} [callerContext] The caller context.
         * @return {IAsyncResult<Array>} The async result.  Responses at index I correlates to request with identifier I.
         */
        executeBatch(requests: IDataServiceRequest[], callerContext?: any): IAsyncResult<any[]>;

    }
}