/**
 * SAMPLE CODE NOTICE
 * 
 * THIS SAMPLE CODE IS MADE AVAILABLE AS IS.  MICROSOFT MAKES NO WARRANTIES, WHETHER EXPRESS OR IMPLIED,
 * OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OR CONDITIONS OF MERCHANTABILITY.
 * THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SAMPLE CODE REMAINS WITH THE USER.
 * NO TECHNICAL SUPPORT IS PROVIDED.  YOU MAY NOT DISTRIBUTE THIS CODE UNLESS YOU HAVE A LICENSE AGREEMENT WITH MICROSOFT THAT ALLOWS YOU TO DO SO.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Retail.Ecommerce.Web.Storefront {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Retail.Ecommerce.Web.Storefront.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Contoso.
        /// </summary>
        public static string AboutContoso {
            get {
                return ResourceManager.GetString("AboutContoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account dashboard.
        /// </summary>
        public static string AccountDashboard {
            get {
                return ResourceManager.GetString("AccountDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book.
        /// </summary>
        public static string AddressBook {
            get {
                return ResourceManager.GetString("AddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All orders can be tracked here..
        /// </summary>
        public static string AllOrdersCanBeTrackedHere {
            get {
                return ResourceManager.GetString("AllOrdersCanBeTrackedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to order history.
        /// </summary>
        public static string BackToOrderHistory {
            get {
                return ResourceManager.GetString("BackToOrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameras.
        /// </summary>
        public static string Cameras {
            get {
                return ResourceManager.GetString("Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout as a guest.
        /// </summary>
        public static string CheckoutAsAGuest {
            get {
                return ResourceManager.GetString("CheckoutAsAGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company information.
        /// </summary>
        public static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        public static string Computers {
            get {
                return ResourceManager.GetString("Computers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with us.
        /// </summary>
        public static string ConnectWithUs {
            get {
                return ResourceManager.GetString("ConnectWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate sales.
        /// </summary>
        public static string CorporateSales {
            get {
                return ResourceManager.GetString("CorporateSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email associated with your existing Contoso Account..
        /// </summary>
        public static string EnterEmailForAccountAssociation {
            get {
                return ResourceManager.GetString("EnterEmailForAccountAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently asked questions.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot my password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift card amount.
        /// </summary>
        public static string GiftCardAmount {
            get {
                return ResourceManager.GetString("GiftCardAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home appliances.
        /// </summary>
        public static string HomeAppliances {
            get {
                return ResourceManager.GetString("HomeAppliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs at Contoso.
        /// </summary>
        public static string JobsAtContoso {
            get {
                return ResourceManager.GetString("JobsAtContoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link account.
        /// </summary>
        public static string LinkAccount {
            get {
                return ResourceManager.GetString("LinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to an existing Contoso account.
        /// </summary>
        public static string LinkContosoAccount {
            get {
                return ResourceManager.GetString("LinkContosoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum price.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum price.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contoso account.
        /// </summary>
        public static string NewContosoAccount {
            get {
                return ResourceManager.GetString("NewContosoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product that you are trying to add does not exist. Please select a different product variant..
        /// </summary>
        public static string NoSuchProduct {
            get {
                return ResourceManager.GetString("NoSuchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order confirmation.
        /// </summary>
        public static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order history.
        /// </summary>
        public static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent orders.
        /// </summary>
        public static string RecentOrders {
            get {
                return ResourceManager.GetString("RecentOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended products.
        /// </summary>
        public static string RecommendedProducts {
            get {
                return ResourceManager.GetString("RecommendedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        public static string SearchBarGo {
            get {
                return ResourceManager.GetString("SearchBarGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for products....
        /// </summary>
        public static string SearchForProducts {
            get {
                return ResourceManager.GetString("SearchForProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with .
        /// </summary>
        public static string SignInWith {
            get {
                return ResourceManager.GetString("SignInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site options.
        /// </summary>
        public static string SiteOptions {
            get {
                return ResourceManager.GetString("SiteOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store catalogs.
        /// </summary>
        public static string StoreCatalogs {
            get {
                return ResourceManager.GetString("StoreCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your order - your order number is.
        /// </summary>
        public static string ThanksForYourOrder {
            get {
                return ResourceManager.GetString("ThanksForYourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV and video.
        /// </summary>
        public static string TvAndVideo {
            get {
                return ResourceManager.GetString("TvAndVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        public static string UnitedStates {
            get {
                return ResourceManager.GetString("UnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your Contoso account.
        /// </summary>
        public static string UseYourContosoAccount {
            get {
                return ResourceManager.GetString("UseYourContosoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all orders.
        /// </summary>
        public static string ViewAllOrders {
            get {
                return ResourceManager.GetString("ViewAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View mobile site.
        /// </summary>
        public static string ViewMobileSite {
            get {
                return ResourceManager.GetString("ViewMobileSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish list.
        /// </summary>
        public static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish lists.
        /// </summary>
        public static string Wishlists {
            get {
                return ResourceManager.GetString("Wishlists", resourceCulture);
            }
        }
    }
}
