/**
 * SAMPLE CODE NOTICE
 * 
 * THIS SAMPLE CODE IS MADE AVAILABLE AS IS.  MICROSOFT MAKES NO WARRANTIES, WHETHER EXPRESS OR IMPLIED,
 * OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OR CONDITIONS OF MERCHANTABILITY.
 * THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SAMPLE CODE REMAINS WITH THE USER.
 * NO TECHNICAL SUPPORT IS PROVIDED.  YOU MAY NOT DISTRIBUTE THIS CODE UNLESS YOU HAVE A LICENSE AGREEMENT WITH MICROSOFT THAT ALLOWS YOU TO DO SO.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Retail.Ecommerce.Sdk.Core.Storefront {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Retail.Ecommerce.Sdk.Core.Storefront.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Included.
        /// </summary>
        internal static string Included {
            get {
                return ResourceManager.GetString("Included", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified ID was not found..
        /// </summary>
        internal static string Microsoft_Dynamics_Commerce_Runtime_ObjectNotFound {
            get {
                return ResourceManager.GetString("Microsoft_Dynamics_Commerce_Runtime_ObjectNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Product info [{0}] unavailable.
        /// </summary>
        internal static string ProductNameUnavailableTemplate {
            get {
                return ResourceManager.GetString("ProductNameUnavailableTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This product is not available in the current store..
        /// </summary>
        internal static string ProductUnavailableDescription {
            get {
                return ResourceManager.GetString("ProductUnavailableDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select shipping options individually..
        /// </summary>
        internal static string ShippingOptionsLineItemSelection {
            get {
                return ResourceManager.GetString("ShippingOptionsLineItemSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pick up from store..
        /// </summary>
        internal static string ShippingOptionsPickup {
            get {
                return ResourceManager.GetString("ShippingOptionsPickup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ship to address..
        /// </summary>
        internal static string ShippingOptionsShipToNewAddress {
            get {
                return ResourceManager.GetString("ShippingOptionsShipToNewAddress", resourceCulture);
            }
        }
    }
}
